spring.application.name=prm-backend

# Server
server.port=8080


# Database Configuration (MongoDB)
spring.data.mongodb.uri=mongodb+srv://hoannaa2011_db_user:02oU9OWEkGnIbpWC@prmcluster.myrtdxw.mongodb.net/prm_db?retryWrites=true&w=majority

# Redis Configuration
# spring.data.redis.host=localhost
# spring.data.redis.port=6379

# JWT Secret (Generate a strong secret in production)
jwt.secret=bXktc3Ryb25nLXNlY3JldC1rZXktdGhhdC1tdXN0LWJlLWF0LWxlYXN0LTMyLWJ5dGVzLWxvbmc=
jwt.expiration=86400000